version: '3.8'

services:
  antink-server:
    build: .
    container_name: antink-server
    privileged: true
    volumes:
      - ./it24_host:/it24_host:rw
      - ./antink_mount:/antink_mount:rw
      - ./antink-logs:/antink-system/antink-logs:rw
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse

  antink-logger:
    image: ubuntu:22.04
    container_name: antink-logger
    depends_on:
      - antink-server
    volumes:
      - ./antink-logs:/antink-system/antink-logs:ro
    command: ["sh", "-c", "tail -f /antink-system/antink-logs/it24.log"]
